# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0002_auto_20170308_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuesr',
            name='user_regdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 8, 12, 13, 25, 894325)),
        ),
    ]
