# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0003_auto_20170308_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuesr',
            name='user_regdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 8, 12, 18, 8, 24356)),
        ),
    ]
