# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0004_auto_20170308_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuesr',
            name='user_regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
